SELECT
	FORMAT((DATEDIFF(day, R.DEBUT_SEJOUR, R.FIN_SEJOUR))/(DATEDIFF(day, 07/03/2014 , 23/03/2014)), PERCENT) AS "Taux Occupation" /* HOLY FUCK-A-MOLOTOV IN YO PUSSY */,
	DISTINCT L.NO_LOGEMENT AS "Numéro Logement",
	T.CODE_TYPE_LOGEMENT AS "Type Logement",
	T.DESCRIPTION AS "Description Logement",
FROM LOGEMENT L
	INNER JOIN SEJOUR S
		ON L.NO_LOGEMENT = S.NO_LOGEMENT
			INNER JOIN RESERVATION R
				ON S.NO_RESERVATION = R.NO_RESERVATION
	INNER JOIN TYPE_LOGEMENT T
		ON L.CODE_TYPE_LOGEMENT = T.CODE_TYPE_LOGEMENT
	INNER JOIN VILLAGE V
		ON L.NOM_VILLAGE = V.NOM_VILLAGE
WHERE
	V.NOM_VILLAGE = "Casa-Dali"
AND R.DEBUT_SEJOUR < 07/03/2014
AND R.FIN_SEJOUR > 23/03/2014
AND	(DATEDIFF(day, R.DEBUT_SEJOUR, R.FIN_SEJOUR))/(DATEDIFF(day, 07/03/2014 , 23/03/2014)) < 0.3
ORDER BY [Taux Occupation];
