SET LINESIZE 120;
SELECT
	L.NO_LOGEMENT AS "Numéro Logement",
	L.NOM_VILLAGE AS "Village",
	V.PAYS AS Pays,
	L.CODE_TYPE_LOGEMENT AS "Type Logement",
	TL.DESCRIPTION AS "Description Logement",
	R.NO_RESERVATION AS "Numéro Réservation",
	R.DEBUT_SEJOUR AS "Première Nuit",
	R.FIN_SEJOUR AS "Dernière Nuit"
FROM LOGEMENT L
	INNER JOIN VILLAGE V
		ON L.NOM_VILLAGE = V.NOM_VILLAGE
	INNER JOIN RESERVATION R
		ON V.NOM_VILLAGE = R.NOM_VILLAGE
	INNER JOIN TYPE_LOGEMENT TL
		ON L.CODE_TYPE_LOGEMENT = TL.CODE_TYPE_LOGEMENT
WHERE L.NO_LOGEMENT = 106
AND	L.NOM_VILLAGE = 'Casa-Dali'
AND R.DEBUT_SEJOUR > TO_DATE('01/04/2014', 'DD/MM/YYYY')
AND R.FIN_SEJOUR < TO_DATE('28/02/2014', 'DD/MM/YYYY')
ORDER BY R.DEBUT_SEJOUR;
