SELECT
	R.NO_CLIENT AS [Numéro Client],
	C.NOM AS [Nom],
	C.PRENOM AS [Prenom],
	C.ADRESSE AS [Adresse],
	C.TEL_DOMICILE AS [Téléphone Domicile]
FROM RESERVATION R
	INNER JOIN CLIENT C
		ON R.NO_CLIENT = C.NO_CLIENT
	INNER JOIN VILLAGE V
		ON R.NOM_VILLAGE = V.NOM_VILLAGE
WHERE
	V.PAYS = "Montréal"
ORDER BY R.NO_CLIENT;