SELECT
	R.NO_RESERVATION AS "Numéro Réservation",
	R.NOM_VILLAGE AS "Nom Village",
	R.DEBUT_SEJOUR AS "Date Départ",
	R.FIN_SEJOUR AS "Date Retour",
	S.NB_PERSONNES AS "Nombre Personnes",
	R.NO_CLIENT AS "Numéro Client",
	C.NOM AS "Nom Client",
	C.PRENOM AS "Prénom Client"
FROM RESERVATION R
	INNER JOIN SEJOUR S
		ON R.NO_RESERVATION = S.NO_RESERVATION
        AND R.NOM_VILLAGE = S.NOM_VILLAGE
	INNER JOIN CLIENT C
		ON R.NO_CLIENT = C.NO_CLIENT
WHERE 
	R.DATE_RESERVATION BETWEEN TO_DATE('12/02/2014', 'DD/MM/YYYY')
AND TO_DATE('20/02/2014', 'DD/MM/YYYY')
ORDER BY
	R.DATE_RESERVATION,
	R.NO_RESERVATION;
