SELECT
	DISTINCT C.NO_CATEGORIE AS [Catégorie Village],
	C.DESCRIPTION AS [Description Catégorie],
	FORMAT(AVG(T.TARIF_UNITAIRE), money) AS [Tarif Moyen]
FROM CATEGORIE_VILLAGE C
	INNER JOIN TARIF_NUIT T
		ON C.NO_CATEGORIE = T.CATEGORIE
ORDER BY C.NO_CATEGORIE;
	