SET LINESIZE 120;
SELECT
	S.NO_LOGEMENT AS [Numéro Logement],
	L.NOM_VILLAGE AS [Village],
	V.PAYS AS Pays,
	L.CODE_TYPE_LOGEMENT AS [Type Logement],
	TL.DESCRIPTION AS [Description Logement]
	R.NO_RESERVATION AS [Numéro Réservation],
	R.DEBUT_SEJOUR AS [Première Nuit],
	R.FIN_SEJOUR AS [Dernière Nuit]
FROM SEJOUR S
	INNER JOIN RESERVATION R
		ON S.NO_RESERVATION = R.NO_RESERVATION
	INNER JOIN LOGEMENT L
		ON S.NO_LOGEMENT = L.NO_LOGEMENT
			INNER JOIN Village V
				ON L.NOM_VILLAGE = V.NOM_VILLAGE
			INNER JOIN TYPE_LOGEMENT TL
				ON L.CODE_TYPE_LOGEMENT = TL.CODE_TYPE_LOGEMENT
WHERE S.NO_LOGEMENT = 106
AND	L.NOM_VILLAGE = "Casa-Dali"
AND R.DEBUT_SEJOUR > 01/04/2014 
AND R.FIN_SEJOUR < 28/02/2014
ORDER BY R.DEBUT_SEJOUR;