SELECT
	L.NO_LOGEMENT AS "Numéro Logement",
    L.CODE_TYPE_LOGEMENT AS "Code du type logement",
    TYPE_LOGEMENT.DESCRIPTION AS "Description"
FROM LOGEMENT L
	LEFT OUTER JOIN SEJOUR S
		ON L.NO_LOGEMENT = S.NO_LOGEMENT AND L.NOM_VILLAGE = S.NOM_VILLAGE
			LEFT JOIN RESERVATION R
				ON S.NO_RESERVATION = R.NO_RESERVATION
    INNER JOIN TYPE_LOGEMENT
        ON L.CODE_TYPE_LOGEMENT = TYPE_LOGEMENT.CODE_TYPE_LOGEMENT
WHERE 
	L.NOM_VILLAGE = 'Casa-Dali'
HAVING
	NVL(SUM(GREATEST(LEAST(R.FIN_SEJOUR, TO_DATE('23/03/2014', 'DD/MM/YYYY')), TO_DATE('07/03/2014', 'DD/MM/YYYY'))- LEAST(GREATEST(R.DEBUT_SEJOUR, TO_DATE('07/03/2014', 'DD/MM/YYYY')), TO_DATE('23/03/2014', 'DD/MM/YYYY'))), 0 ) = 0
GROUP BY L.NO_LOGEMENT, L.CODE_TYPE_LOGEMENT, TYPE_LOGEMENT.DESCRIPTION
ORDER BY L.NO_LOGEMENT;
