SELECT
	TN.TYPE_LOGEMENT AS "Type Logement",
	TL.DESCRIPTION AS "Description Logement",
	TN.CATEGORIE AS "Catégorie Village",
	C.DESCRIPTION AS "Catégorie Village",
	TO_CHAR(TN.TARIF_UNITAIRE, '9,999.00') || '$Can' AS "Prix/Nuit/Personne"
FROM TARIF_NUIT TN
	INNER JOIN TYPE_LOGEMENT TL
		ON TN.TYPE_LOGEMENT = TL.CODE_TYPE_LOGEMENT
	INNER JOIN CATEGORIE_VILLAGE C
		ON TN.CATEGORIE = C.NO_CATEGORIE
WHERE TN.TYPE_LOGEMENT = 'D3'
ORDER BY TN.CATEGORIE;
		
