SELECT
	DISTINCT L.NO_LOGEMENT AS [Numéro Logement],
	T.CODE_TYPE_LOGEMENT AS [Type Logement],
	T.DESCRIPTION AS [Description Logement],
FROM LOGEMENT L
	LEFT JOIN JOIN SEJOUR S
		ON L.NO_LOGEMENT = S.NO_LOGEMENT
			LEFT JOIN RESERVATION R
				ON S.NO_RESERVATION = R.NO_RESERVATION
	INNER JOIN TYPE_LOGEMENT T
		ON L.CODE_TYPE_LOGEMENT = T.CODE_TYPE_LOGEMENT
	INNER JOIN VILLAGE V
		ON L.NOM_VILLAGE = V.NOM_VILLAGE
WHERE
	V.NOM_VILLAGE = "Casa-Dali"
AND R.DEBUT_SEJOUR < 17/03/2014
AND R.FIN_SEJOUR > 23/03/2014
AND SUM(DATEDIFF(day, R.DEBUT_SEJOUR, R.FIN_SEJOUR)) = 0
ORDER BY [Taux Occupation];