SET LINESIZE 120;
SELECT 
	V.NOM_VILLAGE AS Nom,
	V.PAYS AS Pays,
	V.NO_CATEGORIE AS [Code Catégorie],
	C.DESCRIPTION AS [Description Catégorie],
	FORMAT(V.PRIX_TRANSPORT, money) AS [Coût Transport Par Personne]
FROM VILLAGE V
		INNER JOIN CATEGORIE_VILLAGE C
			ON	V.NO_CATEGORIE = C.NO_CATEGORIE
ORDER BY
	V.PAYS,
	V.NO_CATEGORIE,
	V.NOM_VILLAGE;
	
