SELECT
	L.NO_LOGEMENT AS "Numéro Logement",
	NVL(SUM(LEAST(R.FIN_SEJOUR, TO_DATE('31/03/2014', 'DD/MM/YYYY')) - GREATEST(R.DEBUT_SEJOUR, TO_DATE('01/03/2014', 'DD/MM/YYYY'))), 0) AS "Nombre Nuits Occupées"
FROM LOGEMENT L
	LEFT OUTER JOIN SEJOUR S
		ON L.NO_LOGEMENT = S.NO_LOGEMENT AND L.NOM_VILLAGE = S.NOM_VILLAGE
			LEFT JOIN RESERVATION R
				ON S.NO_RESERVATION = R.NO_RESERVATION
WHERE 
	L.NOM_VILLAGE = 'Casa-Dali'
GROUP BY L.NO_LOGEMENT
ORDER BY L.NO_LOGEMENT;
