SELECT
	R.NO_RESERVATION AS "Numéro Réservation",
	TO_CHAR(R.DATE_RESERVATION, 'DD/MM/YYYY') AS "Date Réservation",
	C.NOM AS "Nom Client",
	C.PRENOM AS "Prenom Client"
FROM RESERVATION R
	INNER JOIN CLIENT C
		ON R.NO_CLIENT = C.NO_CLIENT
WHERE R.NO_RESERVATION NOT IN (SELECT NO_RESERVATION FROM SEJOUR)
ORDER BY R.NO_RESERVATION;
