SELECT
	DISTINCT L.NO_LOGEMENT AS [Numéro Logement],
	SUM(DATEDIFF(day, R.DEBUT_SEJOUR, R.FIN_SEJOUR)) AS [Nombre Nuits Occupées]
FROM LOGEMENT L
	INNER JOIN VILAGE V
		ON V.NOM_VILLAGE = L.NOM_VILLAGE
	INNER JOIN SEJOUR S
		ON L.NO_LOGEMENT = S.NO_LOGEMENT
			INNER JOIN	RESERVATION R
				ON S.NO_RESERVATION = R.NO_RESERVATION
WHERE 
	V.NOM_VILLAGE = "Casa-Dali"
AND R.DEBUT_SEJOUR > 01/04/2014 
AND R.FIN_SEJOUR < 28/02/2014
ORDER BY L.NO_LOGEMENT;