SELECT
	DISTINCT C.NO_CATEGORIE AS "Catégorie Village",
	C.DESCRIPTION AS "Description Catégorie",
	TO_CHAR(AVG(T.TARIF_UNITAIRE), '9,999.00') AS "Tarif Moyen"
FROM CATEGORIE_VILLAGE C
	INNER JOIN TARIF_NUIT T
		ON C.NO_CATEGORIE = T.CATEGORIE
GROUP BY C.NO_CATEGORIE, C.DESCRIPTION
ORDER BY C.NO_CATEGORIE;
