SELECT
	NVL(SUM(GREATEST(LEAST(R.FIN_SEJOUR, TO_DATE('23/03/2014', 'DD/MM/YYYY')), TO_DATE('07/03/2014', 'DD/MM/YYYY'))- LEAST(GREATEST(R.DEBUT_SEJOUR, TO_DATE('07/03/2014', 'DD/MM/YYYY')), TO_DATE('23/03/2014', 'DD/MM/YYYY'))), 0 )/ 16 * 100 || '%' AS "Taux d'occupation",
	L.NO_LOGEMENT AS "Numéro Logement",
    L.CODE_TYPE_LOGEMENT AS "Code du type du logement",
    TL.DESCRIPTION AS "Description"
FROM LOGEMENT L
	LEFT OUTER JOIN SEJOUR S
		ON L.NO_LOGEMENT = S.NO_LOGEMENT AND L.NOM_VILLAGE = S.NOM_VILLAGE
			LEFT JOIN RESERVATION R
				ON S.NO_RESERVATION = R.NO_RESERVATION
    INNER JOIN TYPE_LOGEMENT TL
        ON L.CODE_TYPE_LOGEMENT = TL.CODE_TYPE_LOGEMENT
WHERE 
	L.NOM_VILLAGE = 'Casa-Dali'
HAVING
	NVL(SUM(GREATEST(LEAST(R.FIN_SEJOUR, TO_DATE('23/03/2014', 'DD/MM/YYYY')), TO_DATE('07/03/2014', 'DD/MM/YYYY'))- LEAST(GREATEST(R.DEBUT_SEJOUR, TO_DATE('07/03/2014', 'DD/MM/YYYY')), TO_DATE('23/03/2014', 'DD/MM/YYYY'))), 0 )/ 16 * 100 < 30
GROUP BY L.NO_LOGEMENT, L.CODE_TYPE_LOGEMENT, TL.DESCRIPTION
ORDER BY "Taux d'occupation";
