SELECT
	R.NO_RESERVATION AS [Numéro Réservation],
	R.NOM_VILLAGE AS [Nom Village],
	R.DEBUT_SEJOUR AS [Date Départ],
	R.FIN_SEJOUR AS [Date Retour],
	S.NB_PERSONNES AS [Nombre Personnes],
	R.NO_CLIENT AS [Numéro Client],
	C.NOM AS [Nom Client],
	C.PRENOM AS [Prénom Client]
FROM RESERVATION R
	INNER JOIN SEJOUR S
		ON R.NO_RESERVATION = S.NO_RESERVATION
	INNER JOIN CLIENT C
		ON R.NO_CLIENT = C.NO_CLIENT
WHERE 
	R.DATE_RESERVATION >= 12/02/2014
AND R.DATE_RESERVATION <= 20/02/2014
ORDER BY
	R.DATE_RESERVATION,
	R.NO_RESERVATION;