SELECT
	R.NO_RESERVATION AS [Numéro Réservation],
	FORMAT(R.DATE_RESERVATION, 'DD/MM/YYYY') AS [Date Réservation],
	C.NOM AS [Nom Client],
	C.PRENOM AS [Prenom Client]
FROM RESERVATION R
	INNER JOIN CLIENT C
		ON R.NO_CLIENT = C.NO_CLIENT
WHERE SEJOUR.NO_RESERVATION <> R.NO_RESERVATION
ORDER BY R.NO_RESERVATION;