/* Table Client */
CREATE TABLE CLIENT (
    NO_CLIENT       NUMERIC(6;0) PRIMARY KEY,
    NOM             VARCHAR2(15) NOT NULL,
    PRENOM          VARCHAR2(10) NOT NULL,
    SEXE            CHAR(1) NOT NULL,
    TEL_DOMICILE    NUMERIC(10;0) NOT NULL,
    ADRESSE         VARCHAR2(50),
    TEL_BUREAU      NUMERIC(10;0)
);

CREATE TABLE RESERVATION (
    NO_RESERVATION      NUMERIC(6;0) PRIMARY KEY,
    DATE_RESERVATION    DATE NOT NULL,
    NO_CLIENT           NUMERIC(6;0) NOT NULL FOREIGN KEY REFERENCES CLIENT(NO_CLIENT),
    NOM_VILLAGE         VARCHAR2(15) NOT NULL FOREIGN KEY REFERENCES VILLAGE(NOM_VILLAGE),
    DEBUT_SEJOUR        DATE NOT NULL,
    FIN_SEJOUR          DATE NOT NULL
);

CREATE TABLE VILLAGE (
    NOM_VILLAGE         VARCHAR2(15) PRIMARY KEY,
    NO_CATEGORIE        SMALLINT NOT NULL FOREIGN KEY REFERENCES CATEGORIE_VILLAGE(NO_CATEGORIE),
    VILLE               VARCHAR2(10) NOT NULL,
    PAYS                VARCHAR2(10) NOT NULL,
    PRIX_TRANSPORT      NUMERIC(6;2) NOT NULL
);

CREATE TABLE CATEGORIE_VILLAGE (
    NO_CATEGORIE        SMALLINT PRIMARY KEY,
    DESCRIPTION         VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE TARIF_NUIT (
    CATEGORIE       SMALLINT NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES CATEGORIE_VILLAGE(NO_CATEGORIE),
    TYPE_LOGEMENT   VARCHAR2(2) NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES TYPE_LOGEMENT(CODE_TYPE_LOGEMENT)
    TARIF_UNITAIRE  NUMERIC(5;2) NOT NULL
);

CREATE TABLE TYPE_LOGEMENT (
    CODE_TYPE_LOGEMENT      VARCHAR2(2) PRIMARY KEY,
    DESCRIPTION             VARCHAR2(35) NOT NULL UNIQUE,
    NB_MAX_PERSONNES        SMALLINT NOT NULL
);

CREATE TABLE LOGEMENT (
    NO_LOGEMENT             SMALLINT PRIMARY KEY,
    NOM_VILLAGE             VARCHAR2(15) PRIMARY KEY FOREIGN KEY REFERENCES VILLAGE(NOM_VILLAGE),
    CODE_TYPE_LOGEMENT      VARCHAR2(15) NOT NULL FOREIGN KEY REFERENCES TYPE_LOGEMENT(CODE_TYPE_LOGEMENT),
    COMMENTAIRE             VARCHAR2(75),
);

CREATE TABLE SEJOUR (
    NO_LOGEMENT             SMALLINT PRIMARY KEY FOREIGN KEY REFERENCES LOGEMENT(NO_LOGEMENT),
    NOM_VILLAGE             VARCHAR2(15) PRIMARY KEY FOREIGN KEY REFERENCES LOGEMENT(NOM_VILLAGE),
    NO_RESERVATION          NUMERIC(6;0) PRIMARY KEY FOREIGN KEY REFERENCES RESERVATION(NO_RESERVATION),
    NB_PERSONNES            SMALLINT NOT NULL
);
